### ISSUE TITLE
How to use it with ReactiveForm

### ISSUE THREAD

**Issue by martinobordin** [matsura/ng2-dual-list-box#1]
Hi, is it possibile to use it with ReactiveForm? Could you please provide a sample?

I tried to use it passing the `formControlName="MySelectedFields"` but I get this
`Error: No value accessor for form control with name: 'MySelectedFields'`.
A normal select binded to the same formControl is working fine.

**Comment by matsura** [comment]
Hello, I have not implemented accessors for ngModel and reactive forms. In the meantime, you can use the outputs I have provided that are called when moving data. I shall implement this shortly. Leaving this open as enhancement.

**Comment by martinobordin** [comment]
@matsura Thanks for the quick response.

**Comment by matsura** [comment]
@martinobordin Implemented. Check the updated readme. New version is on npm.
