### ISSUE TITLE
Validation attribute

### ISSUE THREAD

**Issue by musaay** [matsura/ng2-dual-list-box#10]
Hi @matsura 

Can you add "required" and "required-message" options for html5 validation.

**Comment by matsura** [comment]
@musaay Can you explain in more detail? Use case etc.

**Comment by musaay** [comment]
For example:
form
<ng2-dual-list-box #appDualListBox [data]="applicationList" [(ngModel)]="selectedApps" name="apps" class="col-md-5 col-sm-12 col-xs-12"
                                           [availableText]="'Applications'" [selectedText]="'Selected Apps'" (onItemsMoved)="setApplications($event)" **[required]="true" [required-message]="Please select at least one app"**></ng2-dual-list-box>
<input type="submit" value="save"/>
form
And when click the submit button, i wanna show error message. But your plugin can not contain required attribute. If you add required attribute to "select" element, i think  the error message will be appear.

**Comment by matsura** [comment]
@musaay Better way to do this without bloating the component would be to have your own logic to check if selectedApps.length is > 0 and then display the message. I will add a new issue as an enhancement where I will allow creation of validator directives.
