### ISSUE TITLE
Set values in the list of selected elements ng2-dual-list-box

### ISSUE THREAD

**Issue by oanillar** [matsura/ng2-dual-list-box#17]
I need to start the view with elements in both list and not only in the list of available elements.
`<ng2-dual-list-box [data]="items"
                   (onAvailableItemSelected)="onAvailableItemSelected($event)"
                   (onSelectedItemsSelected)="onSelectedItemsSelected($event)"
                   (onItemsMoved)="onItemsMoved($event)"></ng2-dual-list-box>`

**Comment by matsura** [comment]
@oanillar In the readme I described that you can use ngModel or formControlName for this.

**Comment by vidyambala** [comment]
Set values in the selected items not working. Tried both ngModel and formControlName.
