### ISSUE TITLE
Pre-populating selected box doesn't work.

### ISSUE THREAD

**Issue by zkispal** [matsura/ng2-dual-list-box#19]
I have the same issue as many others before. I'd like to implement a component where certain users are promoted to assistants. I want to pre-populate the selected box with those who are already privileged. 
I'm binding to selected with NgModel. All variables are populated  from the data source still the selected box is empty.
My template:

`
<div class="row">
  <div class="col-md-8 col-md-offset-2">
    <ng2-dual-list-box [data]="sempais"
                       valueField="ID"
                      textField="name"
                      (onAvailableItemSelected)="log($event)"
                      (onSelectedItemsSelected)="log($event)"
                      (onItemsMoved)="log($event)"
                      [(ngModel)]="selected"
                       availableText = "Sempai"
                       selectedText = "Asszisztens">
    </ng2-dual-list-box>
  </div>
</div>

<div>
  <p>sempais: {{sempais | json}} <br>assistants: {{assistants | json}} <br>selected: {{selected | json}} </p>
</div>
`

My module: 
`@Component({
  selector: 'app-rolechange',
  templateUrl: './rolechange.component.html',
  styleUrls: ['./rolechange.component.css']
})
export class RolechangeComponent implements OnInit {

sempais: Array<{ID: string, name: string}> ;
assistants: Array<{ID: string, name: string}>;
selected: string[] = [];
assistantid = 13;

  constructor(private dataService: DataService) { }

  ngOnInit() {
    this.loadsempais();
    this.loadassistants();
  }

  loadsempais() {

    this.dataService.getsempais()
        .map(res => res.map(elem => this.idToString(elem)))
        .subscribe( sempais => {this.sempais = sempais;
                                 console.log('sempai type: ' + typeof(sempais[0].ID)); },
                    err => console.log(err));
  }

  loadassistants() {
    this.dataService.getroleholder(this.assistantid)
        .map(res => res.map(elem => this.idToString(elem)))
        .subscribe(assistants => {this.assistants = assistants; 
                                  console.log('sempai type: ' + typeof(assistants[0].ID));
                                  this.assistants.forEach(elem => this.selected.push(elem.ID));},
                  err => console.log(err));
  }

idToString(i:Options) {
  
  let o: {ID: string, name: string} = {ID: '', name: ''};
  o.ID = i.ID.toString();
  o.name = i.name;

  return o;
}

}`

I even wrote a separate function to transform the ID from number to string as I thought the issue is with the data type mismatch of the ID field. (I'm getting the ID:name key-value pair in a number:string type.) 

![image](https://user-images.githubusercontent.com/35352734/35760276-8244b918-087f-11e8-8a9a-2b994935bd25.png)

Made search on StackOwerflow but found only questions with no answers. Now I'm clueless.

**Comment by zkispal** [comment]
No worries, finally used an other component. Couldn't solve the issue.

**Comment by gauravshri12** [comment]
What other component you have used, since i am also facing same issue.

**Comment by zkispal** [comment]
Hi,

I ended up using angular-dual-listbox.
https://github.com/czeckd/angular-dual-listbox
Best regards

Zsolt
