### ISSUE TITLE
Add an @Input in order to set the text in the Filter input

### ISSUE THREAD

**Issue by martinobordin** [matsura/ng2-dual-list-box#5]
Hi, could you please add an @input in order to set the text for the filter input from the outside?

Right now is "Filter..." but I'd need to change it.

Thanks

**Comment by matsura** [comment]
Implemented.

**Comment by martinobordin** [comment]
Sorry @matsura, probably I haven't explained myself well. What I meant was to have access to the placeholder text for the 2 input filter  in order to pass a custom text (i.e: from "Filter..." to "Write here to filter the items"). It's not so important, do it when you have time. Thanks again for the support and for the great control

**Comment by matsura** [comment]
@martinobordin This has been implemented. Consult the docs for the input names.
