### ISSUE TITLE
Default Selected Value Not Working

### ISSUE THREAD

**Issue by musaay** [matsura/ng2-dual-list-box#7]
@matsura

my ngModel is: applications: string[]=["1"];

applicationList: [{id=1, name="Test App"}];

<ng2-dual-list-box [data]="applicationList" [(ngModel)]="applications" name="apps" [availableText]="'Applications'" [selectedText]="'Selected Apps'">

But still default selection not working

**Comment by matsura** [comment]
@musaay This has now been fixed. Sorry for the delay(was on vacation).

**Comment by GERRYPALIMA** [comment]
Hi There, What should be the start script?


  "name": "react-dual-listbox-test",
  "version": "1.2.0",
  "description": "A feature-rich dual listbox for React.",
  "author": "Jake Zatecky",
  "scripts": {
    "build": "gulp build",
    "examples": "gulp examples",
    "gh-deploy": "git subtree push --prefix examples/dist origin gh-pages",
    "prepublishOnly": "gulp build",
    "test": "gulp test",
     "start": "index.html"

**Comment by jagadeeshrampati** [comment]
@matsura  I am using the latest version but still facing this issue.

**Comment by robsonflorentino** [comment]
Me too!
