### ISSUE TITLE
Subscribe does't work

### ISSUE THREAD

**Issue by DenisIforium** [matsura/ng2-dual-list-box#8]
Example: 
`        this.adminProfiles = [
            {
                id: "1",
                name: "Antonito"
            },
            {
                id: "2",
                name: "Bonito"
            }
        ];
        this.adminProfileService.getAllAdminProfiles().subscribe(
            data => {
                data.map((adminProfile: any) => this.adminProfiles.push({ id: adminProfile.id, name: adminProfile.name}));
                console.log(this.adminProfiles);
            },
            error => console.log(error)
        );`

They UI list won't be updated after the request is finished, will see only initial 2 arrays.

**Comment by matsura** [comment]
@DenisIforium First of all sorry for not answering in a long time, I was on vacation and had work to do after my return.

What you should do is to replace the array instance completely, like this:

```
this.adminProfiles = [ { id: "1", name: "Antonito" }, { id: "2", name: "Bonito" } ]; 
this.adminProfileService.getAllAdminProfiles().subscribe( data => { 
    this.adminProfiles = [...this.adminProfiles, ...data]; });
```

This will trigger the setter.

**Comment by Barsun** [comment]
thanks
