### ISSUE TITLE
How to programmatically reset the list of selected items

### ISSUE THREAD

**Issue by ReneIllger** [matsura/ng2-dual-list-box#9]
Is it possible to reset the list of selected items? 
I use the list in a reactive form and i used `this.form.controls['selectedValues'].setValue([""]);` to reset the list. The underlying array set to an empty array but the left column in the component is still showing the values.

Thanks in advance for helping.

**Comment by matsura** [comment]
Closed due to no response.

**Comment by burstfour** [comment]
Hello @matsura I have the same issue too.
The values still not returned to the left box even if I already called reset() to reset the reactive form.
